application: drivebox-test 
version: 4
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: static

- url: /admin/.*
  script: admin.app
  login: admin
 # secure: always

- url: /.*
  script: index.app
  secure: always